import { Component, OnInit, inject, DestroyRef, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { RouterLink, Router } from '@angular/router';
import { finalize } from 'rxjs';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { PharmacyService } from '../services/pharmacy.service';
import { MedicineCategory, Manufacturer } from '../models/medicine.model';
@Component({
  selector: 'app-medicine-add',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterLink],
  templateUrl: './medicine-add.html',
  styleUrl: './medicine-add.css'
})
export class MedicineAdd implements OnInit {
  form!: FormGroup;
  categories:    MedicineCategory[] = [];
  manufacturers: Manufacturer[]     = [];
  submitting = false;
  loading    = true;
  errorMsg   = '';
  successMsg = '';

  private destroyRef = inject(DestroyRef);
  private cdr        = inject(ChangeDetectorRef);

  constructor(
    private fb: FormBuilder,
    private pharmacyService: PharmacyService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.form = this.fb.group({
      medicineCode:   [{ value: '', disabled: true }],  // auto-generated by backend, readonly
      medicineName:   ['', [
        Validators.required,
        Validators.minLength(2),
        Validators.maxLength(100),
        Validators.pattern(/^[a-zA-Z0-9\s\-\.\(\)\/&']+$/)
      ]],
      genericName:    ['', [
        Validators.maxLength(100),
        Validators.pattern(/^[a-zA-Z0-9\s\-\.]*$/)
      ]],
      categoryId:     [0, [Validators.required, Validators.min(1)]],
      manufacturerId: [0, [Validators.required, Validators.min(1)]],
      unit:           ['', [
        Validators.maxLength(50),
        Validators.pattern(/^[a-zA-Z0-9\s\.\/]*$/)
      ]],
      unitPrice:      [null, [
        Validators.required,
        Validators.min(0.01),
        Validators.max(99999.99)
      ]],
      reorderLevel:   [0, [
        Validators.min(0),
        Validators.max(99999)
      ]],
      isActive:       [true]
    });

    this.pharmacyService.getNewMedicineMeta().pipe(
      takeUntilDestroyed(this.destroyRef),
      finalize(() => { this.loading = false; this.cdr.markForCheck(); })
    ).subscribe({
      next: (meta) => {
        this.categories    = meta.categories;
        this.manufacturers = meta.manufacturers;
        this.form.patchValue({ medicineCode: meta.nextMedicineCode });
      },
      error: () => { this.errorMsg = 'Failed to load form data. Please refresh and try again.'; }
    });
  }

  f(name: string) { return this.form.get(name); }

  onSubmit(): void {
    if (this.form.invalid) { this.form.markAllAsTouched(); return; }
    this.submitting = true;
    this.errorMsg   = '';
    this.successMsg = '';

    // Trim string fields before submitting; getRawValue() includes disabled medicineCode
    const value = this.form.getRawValue();
    value.medicineName = value.medicineName?.trim();
    value.genericName  = value.genericName?.trim() || null;
    value.unit         = value.unit?.trim() || null;

    this.pharmacyService.createMedicine(value).pipe(
      takeUntilDestroyed(this.destroyRef),
      finalize(() => { this.submitting = false; this.cdr.markForCheck(); })
    ).subscribe({
      next: (res) => {
        this.successMsg = res.message || 'Medicine added successfully.';
        setTimeout(() => this.router.navigate(['/pharmacy/medicine']), 800);
      },
      error: (err) => {
        if (err?.error) {
          const errors = err.error.errors || err.error;
          const msgs: string[] = [];
          if (typeof errors === 'object') {
            Object.values(errors).forEach((v: any) => {
              if (Array.isArray(v)) msgs.push(...v); else msgs.push(String(v));
            });
          }
          this.errorMsg = msgs.length ? msgs.join(' | ') : (err.error?.message || 'Failed to add medicine.');
        } else {
          this.errorMsg = 'Failed to add medicine. Please try again.';
        }
      }
    });
  }
}
